
//=========================================
//                  USER
//=========================================
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';

//=========================================
//                 MOVIE
//=========================================
export const LOAD_MOVIES_REQUEST = 'LOAD_MOVIES_REQUEST';
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_FAILURE = 'LOAD_MOVIES_FAILURE';

export const LOAD_MOVIE_DETAIL_REQUEST = 'LOAD_MOVIE_DETAIL_REQUEST';
export const LOAD_MOVIE_DETAIL_SUCCESS = 'LOAD_MOVIE_DETAIL_SUCCESS';
export const LOAD_MOVIE_DETAIL_FAILURE = 'LOAD_MOVIE_DETAIL_FAILURE';

export const LOAD_MOVIE_TRAILER_REQUEST = 'LOAD_MOVIE_TRAILER_REQUEST';
export const LOAD_MOVIE_TRAILER_SUCCESS = 'LOAD_MOVIE_TRAILER_SUCCESS';
export const LOAD_MOVIE_TRAILER_FAILURE = 'LOAD_MOVIE_TRAILER_FAILURE';

export const LOAD_MOVIE_CASTING_REQUEST = 'LOAD_MOVIE_CASTING_REQUEST';
export const LOAD_MOVIE_CASTING_SUCCESS = 'LOAD_MOVIE_CASTING_SUCCESS';
export const LOAD_MOVIE_CASTING_FAILURE = 'LOAD_MOVIE_CASTING_FAILURE';

//=========================================
//                 FAVORITE
//=========================================
export const LOAD_FAVORITE_NUMBER_REQUEST = 'LOAD_FAVORITE_NUMBER_REQUEST';
export const LOAD_FAVORITE_NUMBER_SUCCESS = 'LOAD_FAVORITE_NUMBER_SUCCESS';
export const LOAD_FAVORITE_NUMBER_FAILURE = 'LOAD_FAVORITE_NUMBER_FAILURE';

export const CHANGE_FAVORITE_REQUEST = 'CHANGE_FAVORITE_REQUEST';
export const CHANGE_FAVORITE_SUCCESS = 'CHANGE_FAVORITE_SUCCESS';
export const CHANGE_FAVORITE_FAILURE = 'CHANGE_FAVORITE_FAILURE';

export const LOAD_IS_FAVORITED_REQUEST = 'LOAD_IS_FAVORITED_REQUEST';
export const LOAD_IS_FAVORITED_SUCCESS = 'LOAD_IS_FAVORITED_SUCCESS';
export const LOAD_IS_FAVORITED_FAILURE = 'LOAD_IS_FAVORITED_FAILURE';

export const LOAD_FAVORITED_LIST_REQUEST = 'LOAD_FAVORITED_LIST_REQUEST';
export const LOAD_FAVORITED_LIST_SUCCESS = 'LOAD_FAVORITED_LIST_SUCCESS';
export const LOAD_FAVORITED_LIST_FAILURE = 'LOAD_FAVORITED_LIST_FAILURE';
