
//=========================================
//                  USER
//=========================================
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';

//=========================================
//                 MOVIE
//=========================================
export const LOAD_MOVIES_REQUEST = 'LOAD_MOVIES_REQUEST';
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_FAILURE = 'LOAD_MOVIES_FAILURE';

export const LOAD_MOVIE_DETAIL_REQUEST = 'LOAD_MOVIE_DETAIL_REQUEST';
export const LOAD_MOVIE_DETAIL_SUCCESS = 'LOAD_MOVIE_DETAIL_SUCCESS';
export const LOAD_MOVIE_DETAIL_FAILURE = 'LOAD_MOVIE_DETAIL_FAILURE';

export const LOAD_MOVIE_TRAILER_REQUEST = 'LOAD_MOVIE_TRAILER_REQUEST';
export const LOAD_MOVIE_TRAILER_SUCCESS = 'LOAD_MOVIE_TRAILER_SUCCESS';
export const LOAD_MOVIE_TRAILER_FAILURE = 'LOAD_MOVIE_TRAILER_FAILURE';

export const LOAD_MOVIE_CASTING_REQUEST = 'LOAD_MOVIE_CASTING_REQUEST';
export const LOAD_MOVIE_CASTING_SUCCESS = 'LOAD_MOVIE_CASTING_SUCCESS';
export const LOAD_MOVIE_CASTING_FAILURE = 'LOAD_MOVIE_CASTING_FAILURE';
